### ISSUE TITLE
Update console app with latest bridge version (async and properties support)

### ISSUE THREAD

**Issue by tjaffri** [openT2T/console#1]
We have updated the bridge with support for new features, and I believe the interface has also changed.

We need to update this app with the new bridge binaries. These are checked in here: https://github.com/openT2T/console/tree/master/cordova-plugin-opent2t/lib

Also, we should make any changes needed to the app for the bridge interface.

**Comment by tjaffri** [comment]
@jasongin is this something we can do please so that we can update all the translators to js-promise versions? Please provide binaries if possible and either I or @sanjaiganesh can take a stab at it.

There are more changes coming down the pipeline for translator formats as discussed, but I would like to take a multi-pass effort and at least integrate the js-promise changes and test a bit before more refactoring.

Thx.

**Comment by jasongin** [comment]
Oh, yes I'll do this soon.

**Comment by tjaffri** [comment]
Awesome, thank you!

**Comment by jasongin** [comment]
Sorry for the delay. PR here: #17
